In [1]:
import sklearn
print(sklearn.__version__)

import warnings
warnings.filterwarnings("ignore")
# Other plots (example)

from src.exp import (
    ExperimentConfig, ExperimentFacade,
    DataReadConfig, PlotManager
)

1.8.0

In [2]:
try:
    from sklearnex import patch_sklearn
    patch_sklearn()
    print("Intel sklearn patch enabled")
except ImportError:
    print("sklearnex not installed; using standard sklearn")

sklearnex not installed; using standard sklearn

In [3]:
data_cfg = DataReadConfig(
    root_dir="Dataset/data",
    recursive=True,
    exclude_filenames=["cclass.csv", "unclean focus.csv","unclean cclass.csv","focus.csv"],  # the excluded files
    add_source_column=False,        # enable this to make additional column filled with the original taken filenames
)

In [4]:
cfg = ExperimentConfig(
    outer_folds=5,
    inner_folds=5,
    n_trials=40,
    seed=42,
    log_target=True
)

In [5]:
models = ["LinearRegression", "DecisionTree", "RandomForest", "SVR", "XGBoost", "NeuralNetwork"]

In [6]:
exp = ExperimentFacade.from_folder(
    data_cfg=data_cfg,
    target="price",
    cfg=cfg,
    model_names=models,
    hparam_json="config/hyperparams.json"
)

# model, year, price, transmission, mileage, fuelType, tax, mpg, engineSize

[schema]
  numerical cols: ['year', 'mileage', 'tax', 'mpg', 'engineSize']
  categorical cols: ['model', 'transmission', 'fuelType']
  target col: ['price']
  mapping: {'model': 'model', 'year': 'year', 'price': 'price', 'transmission': 'transmission', 'mileage': 'mileage', 'fuelType': 'fuelType', 'tax': 'tax', 'mpg': 'mpg', 'engineSize': 'engineSize'}

In [ ]:
results = exp.run()

[I 2026-02-24 07:22:07,364] A new study created in memory with name: LinearRegression_OuterFold_1_residual_cfg_base
[I 2026-02-24 07:22:11,194] Trial 0 finished with value: 2119.6030740614124 and parameters: {}. Best is trial 0 with value: 2119.6030740614124.
[I 2026-02-24 07:22:11,261] Trial 1 finished with value: 2119.6030740614124 and parameters: {}. Best is trial 0 with value: 2119.6030740614124.
[I 2026-02-24 07:22:11,315] Trial 2 finished with value: 2119.6030740614124 and parameters: {}. Best is trial 0 with value: 2119.6030740614124.
[I 2026-02-24 07:22:11,359] Trial 3 finished with value: 2119.6030740614124 and parameters: {}. Best is trial 0 with value: 2119.6030740614124.
[I 2026-02-24 07:22:11,401] Trial 4 finished with value: 2119.6030740614124 and parameters: {}. Best is trial 0 with value: 2119.6030740614124.
[I 2026-02-24 07:22:11,447] Trial 5 finished with value: 2119.6030740614124 and parameters: {}. Best is trial 0 with value: 2119.6030740614124.
[I 2026-02-24 07:22:11,995] A new study created in memory with name: DecisionTree_OuterFold_1_residual_cfg_base
[I 2026-02-24 07:22:18,227] Trial 0 finished with value: 1386.589907938689 and parameters: {'min_samples_split': 7}. Best is trial 0 with value: 1386.589907938689.
[I 2026-02-24 07:22:22,127] Trial 1 finished with value: 1359.6394814390549 and parameters: {'min_samples_split': 38}. Best is trial 1 with value: 1359.6394814390549.
[I 2026-02-24 07:22:25,698] Trial 2 finished with value: 1345.3452931084764 and parameters: {'min_samples_split': 30}. Best is trial 2 with value: 1345.3452931084764.
[I 2026-02-24 07:22:30,350] Trial 3 finished with value: 1334.8265241948825 and parameters: {'min_samples_split': 24}. Best is trial 3 with value: 1334.8265241948825.
[I 2026-02-24 07:22:34,127] Trial 4 finished with value: 1334.4242205598014 and parameters: {'min_samples_split': 20}. Best is trial 4 with value: 1334.4242205598014.
[I 2026-02-24 07:22:40,142] Trial 5 finished with value: 1333.171112842011 and parameters: {'min_samples_split': 15}. Best is trial 5 with value: 1333.171112842011.
[I 2026-02-24 07:22:44,187] Trial 6 finished with value: 1349.0039424183221 and parameters: {'min_samples_split': 34}. Best is trial 5 with value: 1333.171112842011.
[I 2026-02-24 07:22:46,836] Trial 7 finished with value: 1332.4193741383497 and parameters: {'min_samples_split': 21}. Best is trial 7 with value: 1332.4193741383497.
[I 2026-02-24 07:22:49,246] Trial 8 finished with value: 1333.171112842011 and parameters: {'min_samples_split': 15}. Best is trial 7 with value: 1332.4193741383497.
[I 2026-02-24 07:22:51,925] Trial 9 finished with value: 1361.9403954244513 and parameters: {'min_samples_split': 40}. Best is trial 7 with value: 1332.4193741383497.
[I 2026-02-24 07:22:52,691] Trial 10 pruned.
[I 2026-02-24 07:22:53,762] Trial 11 pruned.
[I 2026-02-24 07:22:55,186] A new study created in memory with name: DecisionTree_OuterFold_1_residual_cfg_ElasticNet
[I 2026-02-24 07:22:59,266] Trial 0 finished with value: 1386.5909156831542 and parameters: {'min_samples_split': 7}. Best is trial 0 with value: 1386.5909156831542.
[I 2026-02-24 07:23:04,724] Trial 1 finished with value: 1359.6475888196044 and parameters: {'min_samples_split': 38}. Best is trial 1 with value: 1359.6475888196044.
[I 2026-02-24 07:23:08,987] Trial 2 finished with value: 1345.4348015829878 and parameters: {'min_samples_split': 30}. Best is trial 2 with value: 1345.4348015829878.
[I 2026-02-24 07:23:13,067] Trial 3 finished with value: 1335.0242154486514 and parameters: {'min_samples_split': 24}. Best is trial 3 with value: 1335.0242154486514.
[I 2026-02-24 07:23:17,186] Trial 4 finished with value: 1334.6573245975092 and parameters: {'min_samples_split': 20}. Best is trial 4 with value: 1334.6573245975092.
[I 2026-02-24 07:23:20,969] Trial 5 finished with value: 1333.3889225953012 and parameters: {'min_samples_split': 15}. Best is trial 5 with value: 1333.3889225953012.
[I 2026-02-24 07:23:24,585] Trial 6 finished with value: 1349.0246207770842 and parameters: {'min_samples_split': 34}. Best is trial 5 with value: 1333.3889225953012.
[I 2026-02-24 07:23:28,166] Trial 7 finished with value: 1332.6468650450204 and parameters: {'min_samples_split': 21}. Best is trial 7 with value: 1332.6468650450204.
[I 2026-02-24 07:23:32,690] Trial 8 finished with value: 1333.3889225953012 and parameters: {'min_samples_split': 15}. Best is trial 7 with value: 1332.6468650450204.
[I 2026-02-24 07:23:37,103] Trial 9 finished with value: 1361.9118435433543 and parameters: {'min_samples_split': 40}. Best is trial 7 with value: 1332.6468650450204.
[I 2026-02-24 07:23:37,849] Trial 10 pruned.
[I 2026-02-24 07:23:38,567] Trial 11 pruned.
[I 2026-02-24 07:23:40,225] A new study created in memory with name: DecisionTree_OuterFold_1_residual_cfg_Huber
[I 2026-02-24 07:24:10,238] Trial 0 finished with value: 1385.4082514494798 and parameters: {'min_samples_split': 7}. Best is trial 0 with value: 1385.4082514494798.
[I 2026-02-24 07:24:38,156] Trial 1 finished with value: 1350.735999870914 and parameters: {'min_samples_split': 38}. Best is trial 1 with value: 1350.735999870914.
[I 2026-02-24 07:25:05,063] Trial 2 finished with value: 1338.076530771035 and parameters: {'min_samples_split': 30}. Best is trial 2 with value: 1338.076530771035.
[I 2026-02-24 07:25:33,590] Trial 3 finished with value: 1330.26246729962 and parameters: {'min_samples_split': 24}. Best is trial 3 with value: 1330.26246729962.
[I 2026-02-24 07:25:58,962] Trial 4 finished with value: 1331.0409521435372 and parameters: {'min_samples_split': 20}. Best is trial 3 with value: 1330.26246729962.
[I 2026-02-24 07:26:24,906] Trial 5 finished with value: 1330.7802644561611 and parameters: {'min_samples_split': 15}. Best is trial 3 with value: 1330.26246729962.
[I 2026-02-24 07:26:50,065] Trial 6 finished with value: 1340.9725399474519 and parameters: {'min_samples_split': 34}. Best is trial 3 with value: 1330.26246729962.
[I 2026-02-24 07:27:13,246] Trial 7 finished with value: 1328.5910897927708 and parameters: {'min_samples_split': 21}. Best is trial 7 with value: 1328.5910897927708.
[I 2026-02-24 07:27:38,381] Trial 8 finished with value: 1330.7802644561611 and parameters: {'min_samples_split': 15}. Best is trial 7 with value: 1328.5910897927708.
[I 2026-02-24 07:28:03,190] Trial 9 finished with value: 1352.1061548059597 and parameters: {'min_samples_split': 40}. Best is trial 7 with value: 1328.5910897927708.
[I 2026-02-24 07:28:07,867] Trial 10 pruned.
[I 2026-02-24 07:28:17,202] Trial 11 pruned.
[I 2026-02-24 07:28:23,378] A new study created in memory with name: DecisionTree_OuterFold_1_residual_cfg_PseudoHuber
[I 2026-02-24 07:28:33,157] Trial 0 finished with value: 1386.3861476043812 and parameters: {'min_samples_split': 7}. Best is trial 0 with value: 1386.3861476043812.
[I 2026-02-24 07:28:43,814] Trial 1 finished with value: 1352.6618440099141 and parameters: {'min_samples_split': 38}. Best is trial 1 with value: 1352.6618440099141.
[I 2026-02-24 07:28:55,450] Trial 2 finished with value: 1339.852508464647 and parameters: {'min_samples_split': 30}. Best is trial 2 with value: 1339.852508464647.
[I 2026-02-24 07:29:08,190] Trial 3 finished with value: 1332.2046101400945 and parameters: {'min_samples_split': 24}. Best is trial 3 with value: 1332.2046101400945.
[I 2026-02-24 07:29:20,864] Trial 4 finished with value: 1332.2479383944378 and parameters: {'min_samples_split': 20}. Best is trial 3 with value: 1332.2046101400945.
[I 2026-02-24 07:29:33,000] Trial 5 finished with value: 1331.8255921074056 and parameters: {'min_samples_split': 15}. Best is trial 5 with value: 1331.8255921074056.
[I 2026-02-24 07:29:43,460] Trial 6 finished with value: 1342.9714407918823 and parameters: {'min_samples_split': 34}. Best is trial 5 with value: 1331.8255921074056.
[I 2026-02-24 07:29:54,423] Trial 7 finished with value: 1330.3894329492061 and parameters: {'min_samples_split': 21}. Best is trial 7 with value: 1330.3894329492061.
[I 2026-02-24 07:30:05,041] Trial 8 finished with value: 1331.8255921074056 and parameters: {'min_samples_split': 15}. Best is trial 7 with value: 1330.3894329492061.
[I 2026-02-24 07:30:14,777] Trial 9 finished with value: 1354.3575437775542 and parameters: {'min_samples_split': 40}. Best is trial 7 with value: 1330.3894329492061.
[I 2026-02-24 07:30:16,874] Trial 10 pruned.
[I 2026-02-24 07:30:19,125] Trial 11 pruned.
[I 2026-02-24 07:30:22,291] A new study created in memory with name: RandomForest_OuterFold_1_residual_cfg_base
[I 2026-02-24 07:52:12,770] Trial 0 finished with value: 1280.9343173475586 and parameters: {'min_samples_split': 7, 'n_estimators': 1542, 'max_samples': 0.7716940609894497, 'min_samples_leaf': 6, 'max_features': 0.8, 'max_depth': 26, 'bootstrap': False}. Best is trial 0 with value: 1280.9343173475586.
[I 2026-02-24 07:58:30,877] Trial 1 finished with value: 1416.0527878257813 and parameters: {'min_samples_split': 49, 'n_estimators': 1042, 'max_samples': 0.6420514222950335, 'min_samples_leaf': 2, 'max_features': 0.3, 'max_depth': 18, 'bootstrap': False}. Best is trial 0 with value: 1280.9343173475586.
[I 2026-02-24 08:21:25,490] Trial 2 finished with value: 1500.4109617064337 and parameters: {'min_samples_split': 27, 'n_estimators': 1890, 'max_samples': 0.8876636363405084, 'min_samples_leaf': 10, 'max_features': 0.8, 'max_depth': 16, 'bootstrap': False}. Best is trial 0 with value: 1280.9343173475586.
[I 2026-02-24 08:23:18,409] Trial 3 finished with value: 1326.652603538435 and parameters: {'min_samples_split': 47, 'n_estimators': 320, 'max_samples': 0.8240669060189575, 'min_samples_leaf': 5, 'max_features': 0.3, 'max_depth': 28, 'bootstrap': False}. Best is trial 0 with value: 1280.9343173475586.
[I 2026-02-24 08:27:00,779] Trial 4 finished with value: 1771.8953416758552 and parameters: {'min_samples_split': 24, 'n_estimators': 1370, 'max_samples': 0.6478116019793928, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'max_depth': 29, 'bootstrap': False}. Best is trial 0 with value: 1280.9343173475586.
[I 2026-02-24 08:28:03,298] Trial 5 finished with value: 2015.0158690148605 and parameters: {'min_samples_split': 14, 'n_estimators': 642, 'max_samples': 0.8513867434867163, 'min_samples_leaf': 2, 'max_features': 'log2', 'max_depth': 39, 'bootstrap': True}. Best is trial 0 with value: 1280.9343173475586.
[I 2026-02-24 08:32:56,803] A new study created in memory with name: RandomForest_OuterFold_1_residual_cfg_ElasticNet
[I 2026-02-24 08:58:14,947] Trial 0 finished with value: 1281.1915089670952 and parameters: {'min_samples_split': 7, 'n_estimators': 1542, 'max_samples': 0.7716940609894497, 'min_samples_leaf': 6, 'max_features': 0.8, 'max_depth': 26, 'bootstrap': False}. Best is trial 0 with value: 1281.1915089670952.
[I 2026-02-24 09:05:18,836] Trial 1 finished with value: 1409.3599881903247 and parameters: {'min_samples_split': 49, 'n_estimators': 1042, 'max_samples': 0.6420514222950335, 'min_samples_leaf': 2, 'max_features': 0.3, 'max_depth': 18, 'bootstrap': False}. Best is trial 0 with value: 1281.1915089670952.
[I 2026-02-24 09:27:18,168] Trial 2 finished with value: 1491.6211549224531 and parameters: {'min_samples_split': 27, 'n_estimators': 1890, 'max_samples': 0.8876636363405084, 'min_samples_leaf': 10, 'max_features': 0.8, 'max_depth': 16, 'bootstrap': False}. Best is trial 0 with value: 1281.1915089670952.
[I 2026-02-24 09:29:11,290] Trial 3 finished with value: 1326.8152967325655 and parameters: {'min_samples_split': 47, 'n_estimators': 320, 'max_samples': 0.8240669060189575, 'min_samples_leaf': 5, 'max_features': 0.3, 'max_depth': 28, 'bootstrap': False}. Best is trial 0 with value: 1281.1915089670952.
[I 2026-02-24 09:32:42,280] Trial 4 finished with value: 1642.6076749135905 and parameters: {'min_samples_split': 24, 'n_estimators': 1370, 'max_samples': 0.6478116019793928, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'max_depth': 29, 'bootstrap': False}. Best is trial 0 with value: 1281.1915089670952.
[I 2026-02-24 09:33:34,920] Trial 5 finished with value: 1712.106256227243 and parameters: {'min_samples_split': 14, 'n_estimators': 642, 'max_samples': 0.8513867434867163, 'min_samples_leaf': 2, 'max_features': 'log2', 'max_depth': 39, 'bootstrap': True}. Best is trial 0 with value: 1281.1915089670952.
[I 2026-02-24 09:38:48,505] A new study created in memory with name: RandomForest_OuterFold_1_residual_cfg_Huber
[I 2026-02-24 09:54:16,588] Trial 0 finished with value: 1254.6125589166086 and parameters: {'min_samples_split': 7, 'n_estimators': 1542, 'max_samples': 0.7716940609894497, 'min_samples_leaf': 6, 'max_features': 0.8, 'max_depth': 26, 'bootstrap': False, 'residual__Huber__epsilon': 2.462482537377837, 'residual__Huber__alpha': 0.0007419858153596109}. Best is trial 0 with value: 1254.6125589166086.
[I 2026-02-24 09:55:29,484] Trial 1 finished with value: 1485.3424472468712 and parameters: {'min_samples_split': 8, 'n_estimators': 275, 'max_samples': 0.8183988808338614, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'max_depth': 25, 'bootstrap': False, 'residual__Huber__epsilon': 2.438318181702542, 'residual__Huber__alpha': 0.0866417498510988}. Best is trial 0 with value: 1254.6125589166086.
[I 2026-02-24 09:56:57,474] Trial 2 finished with value: 1802.3970932250934 and parameters: {'min_samples_split': 13, 'n_estimators': 374, 'max_samples': 0.6737245998351543, 'min_samples_leaf': 8, 'max_features': 0.8, 'max_depth': 6, 'bootstrap': True, 'residual__Huber__epsilon': 1.8036376415963777, 'residual__Huber__alpha': 1.7446839992329046e-05}. Best is trial 0 with value: 1254.6125589166086.
[I 2026-02-24 10:28:41,701] Trial 3 finished with value: 1403.5905423640104 and parameters: {'min_samples_split': 45, 'n_estimators': 1600, 'max_samples': 0.8010359087299617, 'min_samples_leaf': 8, 'max_features': 0.3, 'max_depth': 19, 'bootstrap': True, 'residual__Huber__epsilon': 1.1063562684879935, 'residual__Huber__alpha': 0.011990932583239567}. Best is trial 0 with value: 1254.6125589166086.
[I 2026-02-24 10:33:52,840] Trial 4 finished with value: 1245.0433865643747 and parameters: {'min_samples_split': 26, 'n_estimators': 1581, 'max_samples': 0.8039275571852551, 'min_samples_leaf': 3, 'max_features': 0.5, 'max_depth': 38, 'bootstrap': True, 'residual__Huber__epsilon': 2.1895796052211103, 'residual__Huber__alpha': 0.006851944299893705}. Best is trial 4 with value: 1245.0433865643747.
[I 2026-02-24 10:37:43,229] Trial 5 finished with value: 1419.8938373031688 and parameters: {'min_samples_split': 49, 'n_estimators': 1960, 'max_samples': 0.7499996374080655, 'min_samples_leaf': 7, 'max_features': 0.3, 'max_depth': 17, 'bootstrap': True, 'residual__Huber__epsilon': 1.0571091986688872, 'residual__Huber__alpha': 0.037024991993361504}. Best is trial 4 with value: 1245.0433865643747.
[I 2026-02-24 10:43:12,005] Trial 6 finished with value: 1387.9828150325477 and parameters: {'min_samples_split': 9, 'n_estimators': 1350, 'max_samples': 0.6300112429633934, 'min_samples_leaf': 10, 'max_features': 0.8, 'max_depth': 28, 'bootstrap': True, 'residual__Huber__epsilon': 1.0201851447964234, 'residual__Huber__alpha': 0.00026508184823690776}. Best is trial 4 with value: 1245.0433865643747.
[I 2026-02-24 10:43:54,313] Trial 7 finished with value: 1812.9802030163246 and parameters: {'min_samples_split': 41, 'n_estimators': 250, 'max_samples': 0.8210316148371506, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'max_depth': 9, 'bootstrap': False, 'residual__Huber__epsilon': 1.7871389342807626, 'residual__Huber__alpha': 0.009941181090580543}. Best is trial 4 with value: 1245.0433865643747.
[I 2026-02-24 10:44:31,326] Trial 8 finished with value: 1790.1849463442327 and parameters: {'min_samples_split': 11, 'n_estimators': 212, 'max_samples': 0.7826394235111456, 'min_samples_leaf': 5, 'max_features': 0.3, 'max_depth': 6, 'bootstrap': True, 'residual__Huber__epsilon': 1.176800236154972, 'residual__Huber__alpha': 0.0001826540275405295}. Best is trial 4 with value: 1245.0433865643747.

In [ ]:
display(exp.summary())
model_summary = exp.summary()["model"]

,model,R2_mean,R2_std,MAE_mean,MAE_std,MedAE_mean,MedAE_std,MSE_mean,MSE_std,RMSE_mean,RMSE_std
0,DecisionTree,0.947015,0.004777,1284.564100,20.977425,801.957289,13.403884,5.155763e+06,4.504636e+05,2268.843307,100.705935
1,DecisionTree+ElasticNet,0.947033,0.004778,1284.716853,20.911955,801.773077,13.791613,5.153990e+06,4.506138e+05,2268.451106,100.744807
2,DecisionTree+Huber,0.947028,0.004767,1284.191780,20.963612,801.494555,14.879842,5.154434e+06,4.493552e+05,2268.559168,100.454733
3,DecisionTree+PseudoHuber,0.947563,0.004401,1280.186754,15.008215,799.439825,12.191988,5.102984e+06,4.223503e+05,2257.379631,95.005086
4,LinearRegression,-2.606856,7.771180,2110.810040,122.029471,1332.976244,7.017524,3.529705e+08,7.606829e+08,11138.970659,16915.000996
5,NeuralNetwork,0.855378,0.100311,1830.907971,72.164376,1152.081836,61.983012,1.410562e+07,9.853634e+06,3616.302983,1133.564112
6,RandomForest,0.959471,0.003362,1133.608924,28.101011,726.758290,16.178567,3.944784e+06,3.311553e+05,1984.748215,83.354356
7,RandomForest+ElasticNet,0.959539,0.003399,1133.912797,28.214816,726.741367,15.160861,3.938128e+06,3.347015e+05,1983.036394,84.367644
8,RandomForest+Huber,0.957119,0.004926,1154.969756,13.543526,735.347621,8.280192,4.173526e+06,4.798110e+05,2040.187671,118.110686
9,RandomForest+PseudoHuber,0.961363,0.004407,1128.428626,16.448138,726.284264,9.470179,3.760864e+06,4.348629e+05,1936.666040,112.854954
10,SVR,0.920724,0.008188,1625.641790,51.428714,1016.857817,34.005589,7.725403e+06,9.147513e+05,2775.690132,161.814745
11,XGBoost+Huber,0.962818,0.004140,1103.754522,21.240820,710.017534,14.369854,3.619053e+06,4.067441e+05,1899.900912,108.568066
12,XGBoost+PseudoHuber,0.964016,0.003518,1089.040097,13.658130,703.470996,10.194467,3.501161e+06,3.290290e+05,1869.440058,89.128521

In [ ]:
model_summary.to_list()

['DecisionTree',
 'DecisionTree+ElasticNet',
 'DecisionTree+Huber',
 'DecisionTree+PseudoHuber',
 'LinearRegression',
 'NeuralNetwork',
 'RandomForest',
 'RandomForest+ElasticNet',
 'RandomForest+Huber',
 'RandomForest+PseudoHuber',
 'SVR',
 'XGBoost+Huber',
 'XGBoost+PseudoHuber']

In [ ]:
sig = exp.significance(
    metric="R2",
    baseline="XGBoost+PseudoHuber",
    models=model_summary.to_list()
)

In [ ]:
display(sig)

,metric,baseline,model,paired_t_p,wilcoxon_p,n_outer_folds
2,R2,XGBoost+PseudoHuber,DecisionTree+Huber,0.000017,0.0625,5
1,R2,XGBoost+PseudoHuber,DecisionTree+ElasticNet,0.000017,0.0625,5
0,R2,XGBoost+PseudoHuber,DecisionTree,0.000017,0.0625,5
3,R2,XGBoost+PseudoHuber,DecisionTree+PseudoHuber,0.000026,0.0625,5
10,R2,XGBoost+PseudoHuber,SVR,0.000236,0.0625,5
8,R2,XGBoost+PseudoHuber,RandomForest+Huber,0.001312,0.0625,5
6,R2,XGBoost+PseudoHuber,RandomForest,0.003513,0.0625,5
7,R2,XGBoost+PseudoHuber,RandomForest+ElasticNet,0.003536,0.0625,5
5,R2,XGBoost+PseudoHuber,NeuralNetwork,0.071710,0.0625,5
9,R2,XGBoost+PseudoHuber,RandomForest+PseudoHuber,0.079200,0.0625,5
11,R2,XGBoost+PseudoHuber,XGBoost+Huber,0.110116,0.1875,5
4,R2,XGBoost+PseudoHuber,LinearRegression,0.362241,0.0625,5

In [ ]:
model_new = [
    'RandomForest',
    'SVR',
    'XGBoost',
    'XGBoost+Huber',
    'XGBoost+PseudoHuber',
    'NeuralNetwork']

In [ ]:
shap_analyzer = exp.shap(models=model_new) #exp.shap(models=model_summary.to_list())

In [ ]:
shap_analyzer.available_models()

['RandomForest',
 'RandomForest+ElasticNet',
 'RandomForest+Huber',
 'RandomForest+PseudoHuber',
 'SVR',
 'XGBoost',
 'XGBoost+Huber',
 'XGBoost+PseudoHuber',
 'NeuralNetwork']

In [ ]:
for m in shap_analyzer.available_models():
    shap_analyzer.beeswarm(m)

Computing SHAP for RandomForest:   0%|          | 0/20 [00:00<?, ?it/s]

:

:

In [ ]:
exp.summary()

,model,R2_mean,R2_std,MAE_mean,MAE_std,MedAE_mean,MedAE_std,MSE_mean,MSE_std,RMSE_mean,RMSE_std
0,DecisionTree,0.947015,0.004777,1284.564100,20.977425,801.957289,13.403884,5.155763e+06,4.504636e+05,2268.843307,100.705935
1,DecisionTree+ElasticNet,0.947033,0.004778,1284.716853,20.911955,801.773077,13.791613,5.153990e+06,4.506138e+05,2268.451106,100.744807
2,DecisionTree+Huber,0.947028,0.004767,1284.191780,20.963612,801.494555,14.879842,5.154434e+06,4.493552e+05,2268.559168,100.454733
3,DecisionTree+PseudoHuber,0.947563,0.004401,1280.186754,15.008215,799.439825,12.191988,5.102984e+06,4.223503e+05,2257.379631,95.005086
4,LinearRegression,-2.606856,7.771180,2110.810040,122.029471,1332.976244,7.017524,3.529705e+08,7.606829e+08,11138.970659,16915.000996
5,NeuralNetwork,0.855378,0.100311,1830.907971,72.164376,1152.081836,61.983012,1.410562e+07,9.853634e+06,3616.302983,1133.564112
6,RandomForest,0.959471,0.003362,1133.608924,28.101011,726.758290,16.178567,3.944784e+06,3.311553e+05,1984.748215,83.354356
7,RandomForest+ElasticNet,0.959539,0.003399,1133.912797,28.214816,726.741367,15.160861,3.938128e+06,3.347015e+05,1983.036394,84.367644
8,RandomForest+Huber,0.957119,0.004926,1154.969756,13.543526,735.347621,8.280192,4.173526e+06,4.798110e+05,2040.187671,118.110686
9,RandomForest+PseudoHuber,0.961363,0.004407,1128.428626,16.448138,726.284264,9.470179,3.760864e+06,4.348629e+05,1936.666040,112.854954
10,SVR,0.920724,0.008188,1625.641790,51.428714,1016.857817,34.005589,7.725403e+06,9.147513e+05,2775.690132,161.814745
11,XGBoost+Huber,0.962818,0.004140,1103.754522,21.240820,710.017534,14.369854,3.619053e+06,4.067441e+05,1899.900912,108.568066
12,XGBoost+PseudoHuber,0.964016,0.003518,1089.040097,13.658130,703.470996,10.194467,3.501161e+06,3.290290e+05,1869.440058,89.128521

In [ ]:
results.to_csv("outputs/experiment_results.csv", index=False)

In [ ]:
pm = PlotManager("outputs/figures/metrics")

In [ ]:
for metric in ["R2", "MAE", "MedAE", "MSE", "RMSE"]:
    is_ascending = metric != "R2" and metric != "NegMSE"
    #fig = plot_point_range_1(results, metric=metric, ascending=is_ascending)
    #fig.savefig(f"outputs/figures/metrics/point_range_{metric.lower()}", dpi=300, bbox_inches="tight")
    fig = pm.plot_point_range(results_df=results, metric=metric, ascending=is_ascending)
    pm.save_fig(fig, f"point_range_{metric.lower()}")

[saved] /Users/macbook/Library/CloudStorage/GoogleDrive-nur.ichsan@gmail.com/My Drive/UNS/2023/Business Intelligence/Paper/Salomo/NewIJAI/outputs/figures/metrics/point_range_r2.png
[saved] /Users/macbook/Library/CloudStorage/GoogleDrive-nur.ichsan@gmail.com/My Drive/UNS/2023/Business Intelligence/Paper/Salomo/NewIJAI/outputs/figures/metrics/point_range_mae.png
[saved] /Users/macbook/Library/CloudStorage/GoogleDrive-nur.ichsan@gmail.com/My Drive/UNS/2023/Business Intelligence/Paper/Salomo/NewIJAI/outputs/figures/metrics/point_range_medae.png
[saved] /Users/macbook/Library/CloudStorage/GoogleDrive-nur.ichsan@gmail.com/My Drive/UNS/2023/Business Intelligence/Paper/Salomo/NewIJAI/outputs/figures/metrics/point_range_mse.png
[saved] /Users/macbook/Library/CloudStorage/GoogleDrive-nur.ichsan@gmail.com/My Drive/UNS/2023/Business Intelligence/Paper/Salomo/NewIJAI/outputs/figures/metrics/point_range_rmse.png

In [ ]:
for metric in ["R2", "MAE", "MedAE", "MSE", "RMSE"]:
    display(exp.significance_matrix(metric=metric))

,metric,model_a,model_b,paired_t_p,wilcoxon_p,n_outer_folds
31,R2,DecisionTree+Huber,XGBoost+Huber,0.000007,0.0625,5
21,R2,DecisionTree+ElasticNet,XGBoost+Huber,0.000007,0.0625,5
10,R2,DecisionTree,XGBoost+Huber,0.000007,0.0625,5
40,R2,DecisionTree+PseudoHuber,XGBoost+Huber,0.000008,0.0625,5
32,R2,DecisionTree+Huber,XGBoost+PseudoHuber,0.000017,0.0625,5
...,...,...,...,...,...,...
24,R2,DecisionTree+Huber,LinearRegression,0.364221,0.0625,5
3,R2,DecisionTree,LinearRegression,0.364222,0.0625,5
47,R2,LinearRegression,SVR,0.367423,0.0625,5
42,R2,LinearRegression,NeuralNetwork,0.369973,0.0625,5
12,R2,DecisionTree+ElasticNet,DecisionTree+Huber,0.542959,0.6250,5

,metric,model_a,model_b,paired_t_p,wilcoxon_p,n_outer_folds
41,MAE,DecisionTree+PseudoHuber,XGBoost+PseudoHuber,0.000003,0.0625,5
56,MAE,NeuralNetwork,XGBoost+PseudoHuber,0.000011,0.0625,5
22,MAE,DecisionTree+ElasticNet,XGBoost+PseudoHuber,0.000013,0.0625,5
11,MAE,DecisionTree,XGBoost+PseudoHuber,0.000013,0.0625,5
32,MAE,DecisionTree+Huber,XGBoost+PseudoHuber,0.000014,0.0625,5
...,...,...,...,...,...,...
13,MAE,DecisionTree+ElasticNet,DecisionTree+PseudoHuber,0.294332,0.1250,5
2,MAE,DecisionTree,DecisionTree+PseudoHuber,0.311386,0.1250,5
23,MAE,DecisionTree+Huber,DecisionTree+PseudoHuber,0.350433,0.3125,5
64,MAE,RandomForest+ElasticNet,RandomForest+PseudoHuber,0.773775,0.6250,5
59,MAE,RandomForest,RandomForest+PseudoHuber,0.785470,0.6250,5

,metric,model_a,model_b,paired_t_p,wilcoxon_p,n_outer_folds
45,MedAE,LinearRegression,RandomForest+Huber,5.959551e-10,0.0625,5
44,MedAE,LinearRegression,RandomForest+ElasticNet,3.508145e-08,0.0625,5
43,MedAE,LinearRegression,RandomForest,4.800095e-08,0.0625,5
46,MedAE,LinearRegression,RandomForest+PseudoHuber,5.225085e-08,0.0625,5
3,MedAE,DecisionTree,LinearRegression,8.272696e-08,0.0625,5
...,...,...,...,...,...,...
12,MedAE,DecisionTree+ElasticNet,DecisionTree+Huber,7.028137e-01,0.8125,5
0,MedAE,DecisionTree,DecisionTree+ElasticNet,7.463916e-01,0.6250,5
64,MedAE,RandomForest+ElasticNet,RandomForest+PseudoHuber,9.581951e-01,0.8125,5
59,MedAE,RandomForest,RandomForest+PseudoHuber,9.584959e-01,0.8125,5
57,MedAE,RandomForest,RandomForest+ElasticNet,9.738640e-01,1.0000,5

,metric,model_a,model_b,paired_t_p,wilcoxon_p,n_outer_folds
31,MSE,DecisionTree+Huber,XGBoost+Huber,0.000002,0.0625,5
21,MSE,DecisionTree+ElasticNet,XGBoost+Huber,0.000002,0.0625,5
10,MSE,DecisionTree,XGBoost+Huber,0.000002,0.0625,5
40,MSE,DecisionTree+PseudoHuber,XGBoost+Huber,0.000004,0.0625,5
38,MSE,DecisionTree+PseudoHuber,RandomForest+PseudoHuber,0.000013,0.0625,5
...,...,...,...,...,...,...
24,MSE,DecisionTree+Huber,LinearRegression,0.364281,0.0625,5
3,MSE,DecisionTree,LinearRegression,0.364282,0.0625,5
47,MSE,LinearRegression,SVR,0.367478,0.0625,5
42,MSE,LinearRegression,NeuralNetwork,0.370004,0.0625,5
12,MSE,DecisionTree+ElasticNet,DecisionTree+Huber,0.551324,0.6250,5

,metric,model_a,model_b,paired_t_p,wilcoxon_p,n_outer_folds
21,RMSE,DecisionTree+ElasticNet,XGBoost+Huber,0.000002,0.0625,5
10,RMSE,DecisionTree,XGBoost+Huber,0.000002,0.0625,5
31,RMSE,DecisionTree+Huber,XGBoost+Huber,0.000002,0.0625,5
32,RMSE,DecisionTree+Huber,XGBoost+PseudoHuber,0.000003,0.0625,5
22,RMSE,DecisionTree+ElasticNet,XGBoost+PseudoHuber,0.000004,0.0625,5
...,...,...,...,...,...,...
59,RMSE,RandomForest,RandomForest+PseudoHuber,0.318602,0.6250,5
47,RMSE,LinearRegression,SVR,0.330175,0.0625,5
64,RMSE,RandomForest+ElasticNet,RandomForest+PseudoHuber,0.330864,0.6250,5
42,RMSE,LinearRegression,NeuralNetwork,0.346823,0.0625,5
12,RMSE,DecisionTree+ElasticNet,DecisionTree+Huber,0.522579,0.6250,5

In [ ]:
exp.save_best_params()

[saved] /Users/macbook/Library/CloudStorage/GoogleDrive-nur.ichsan@gmail.com/My Drive/UNS/2023/Business Intelligence/Paper/Salomo/NewIJAI/outputs/best_params/best_params.json